# Generated by Django 2.0.2 on 2018-02-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('ativo', models.BooleanField(default=True, verbose_name='Usuário Ativo?')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('username', models.CharField(max_length=255, verbose_name='Nome pelo qual deseja ser tratado')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/contas', verbose_name='Imagem')),
                ('admin', models.BooleanField(default=False)),
                ('superusuario', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Usuários',
                'db_table': 'contas_usuarios',
                'verbose_name': 'Usuário',
            },
        ),
    ]
