# Generated by Django 2.0.2 on 2018-02-23 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Base',
                'db_table': 'main_bases',
                'verbose_name_plural': 'Base',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastrado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data da última atualizacao')),
                ('titulo', models.CharField(max_length=300, unique=True, verbose_name='Titulo')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('resumo_url', models.TextField(blank=True, null=True, verbose_name='URL Resumo')),
                ('autores', models.TextField(blank=True, null=True, verbose_name='Autores')),
                ('citado_papers', models.IntegerField(blank=True, null=True, verbose_name='Número de papers que citaram o artigo')),
                ('citado_patentes', models.IntegerField(blank=True, null=True, verbose_name='Número de patentes que citaram o artigo')),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOi')),
                ('nome_completo_autor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo de um autor')),
                ('html_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome completo de um autor')),
                ('palavras_chaves', models.TextField(blank=True, null=True, verbose_name='Termos do autor e da revista')),
                ('pdf_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL do pdf')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data da pubicação')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank do artigo na pesquisa')),
                ('arquivo', models.FileField(upload_to='arquivos', verbose_name='Arquivo do documento')),
                ('bases', models.ManyToManyField(to='main.Base')),
                ('cadastrado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'db_table': 'main_documentos',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Fichamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastrado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data da última atualizacao')),
                ('caracteristicas_dados', models.TextField(blank=True, verbose_name='Características dos dados analisados')),
                ('citacoes', models.TextField(blank=True, verbose_name='Citações')),
                ('anotacoes', models.TextField(blank=True, verbose_name='Anotações gerais')),
                ('cadastrado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichamentos', to='main.Documento')),
            ],
            options={
                'verbose_name': 'fichamentos',
                'db_table': 'main_fichamentos',
                'verbose_name_plural': 'fichamentos',
            },
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastrado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data da última atualizacao')),
                ('nome', models.CharField(max_length=90, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_revisoes', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documentos', models.ManyToManyField(blank=True, null=True, to='main.Documento')),
                ('usuarios', models.ManyToManyField(related_name='revisoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisão',
                'db_table': 'main_revisoes',
                'verbose_name_plural': 'Revisões',
            },
        ),
        migrations.AddField(
            model_name='fichamento',
            name='revisao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichamentos', to='main.Revisao'),
        ),
    ]
