# Generated by Django 2.0.2 on 2018-03-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180228_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='citado_papers_scholar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de citações pelo Google Scholar'),
        ),
        migrations.AddField(
            model_name='documento',
            name='citado_papers_scholar_data',
            field=models.DateField(blank=True, null=True, verbose_name='Rank do artigo na pesquisa'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da publicação'),
        ),
    ]
