# Generated by Django 2.0.2 on 2018-03-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180302_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='citado_papers_scholar_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rank do artigo na pesquisa'),
        ),
    ]
