# Generated by Django 2.0.2 on 2018-03-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_load_bases_fixture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='titulo',
            field=models.CharField(max_length=2048, verbose_name='Titulo'),
        ),
    ]
