# Generated by Django 2.0.2 on 2018-03-06 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20180306_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastrado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data da última atualizacao')),
                ('nome', models.CharField(max_length=20, verbose_name='nome')),
                ('cor', models.CharField(max_length=6, verbose_name='nome')),
                ('cadastrado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('revisao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Revisao')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
                'db_table': 'main_tags',
            },
        ),
    ]
