# Generated by Django 2.0.2 on 2018-03-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='fichamentos',
            field=models.ManyToManyField(related_name='tags', to='main.Documento'),
        ),
    ]
