# Generated by Django 2.0.2 on 2018-03-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_tag_fichamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='cor',
            field=models.CharField(max_length=7, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
    ]
