# Generated by Django 2.0.2 on 2018-03-08 13:06

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180307_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamento',
            name='anotacoes',
            field=martor.models.MartorField(blank=True, verbose_name='Anotações gerais'),
        ),
        migrations.AlterField(
            model_name='fichamento',
            name='caracteristicas_dados',
            field=martor.models.MartorField(blank=True, verbose_name='Características dos dados analisados'),
        ),
        migrations.AlterField(
            model_name='fichamento',
            name='citacoes',
            field=martor.models.MartorField(blank=True, verbose_name='Citações'),
        ),
    ]
