# Generated by Django 2.0.2 on 2018-03-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180307_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='fichamentos',
        ),
        migrations.AddField(
            model_name='fichamento',
            name='tags',
            field=models.ManyToManyField(related_name='fichamentos', to='main.Tag'),
        ),
    ]
