# Generated by Django 2.0.2 on 2018-03-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180308_1006'),
        ('main', '0011_auto_20180308_1715'),
    ]

    operations = [
    ]
