# Generated by Django 2.0.2 on 2018-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_20180308_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos', verbose_name='Arquivo do documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='citado_papers_scholar_data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de verificação no Google Scholar'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DOI'),
        ),
    ]
