# Generated by Django 2.0.2 on 2018-02-08 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastrado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data da última atualizacao')),
                ('nome', models.CharField(max_length=90, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adm_revisoes', to=settings.AUTH_USER_MODEL)),
                ('cadastrado_por', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarios', models.ManyToManyField(related_name='revisoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisão',
                'verbose_name_plural': 'Revisões',
                'db_table': 'main_revisoes',
            },
        ),
    ]
