# Generated by Django 2.0.2 on 2018-02-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_documento_fichamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='citing_patents',
            new_name='citado_patentes',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='fichamento',
        ),
        migrations.AddField(
            model_name='revisao',
            name='documentos',
            field=models.ManyToManyField(to='main.Documento'),
        ),
    ]
