# Generated by Django 2.0.2 on 2018-02-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180224_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='nome_completo_autor',
        ),
        migrations.AddField(
            model_name='documento',
            name='revista',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Revista'),
        ),
    ]
