# Generated by Django 2.0.2 on 2018-02-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180209_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='termos_revista',
            new_name='chaves_revista',
        ),
        migrations.RenameField(
            model_name='documento',
            old_name='index_termos',
            new_name='palavras_chaves',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='autores_termos',
        ),
        migrations.AddField(
            model_name='documento',
            name='chaves_autores',
            field=models.TextField(blank=True, null=True, verbose_name='Palavras chaves fornecidas pelo autor que descrevem o documento'),
        ),
    ]
