# Generated by Django 2.0.2 on 2018-03-05 18:59

from django.db import migrations
from django.core.management import call_command

fixture = "atena/apps/main/fixtures/bases.yaml"

def load_fixture(apps, schema_editor):
    "Chamando o comando de carregar a fixture de bases"
    call_command('loaddata', fixture, app_label='yourapp')

def unload_fixture(apps, schema_editor):
    "Brutalmente deletando todas as entradas de main.models.Bases"

    MyModel = apps.get_model("main", "Bases")
    MyModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180302_0237'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
